# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js v18.15.0
              uses: actions/setup-node@v3
              with:
                  node-version: 18.15.0
                  cache: 'npm'

            - run: npm ci
            - run: npm run build

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                  aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  aws-region: us-east-1

            - name: Copy files to the S3 bucket
              run: |
                  aws s3 sync ./build s3://guychienll.dev

            - name: Invalidate CDN Cache
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION_ID}} --paths '/*'

            - name: algolia indexing
              run: |
                  echo APPLICATION_ID=${{ secrets.APPLICATION_ID }} >> .env
                  echo API_KEY=${{ secrets.API_KEY }} >> .env
                  make algolia-scraper
